server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/BOBbankDB
    username: postgres
    password: root 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true 
  instance:
    prefer-ip-address: true

jwt:
  secret: 7465d4c4e2c69550f67a35c35f138a997ef55aa75132a12baee7bb88b3cec75c0dcfbc75bfc9a790bea95c9965acd30f275418929870324448cced41e477b51d
  expiration: 3600000


#Spring Security Configuration
#   security:
#     user:
#       name: admin
#       password: admin

#exclude spring security from application
  # autoconfigure:
  #   exclude:
  #   - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration