
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id:  auth-service
            uri: lb://auth-service
            predicates:
            - Path=/auth/**
            # filters:
            # - StripPrefix=1    # it will remove auth before redirecting 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    ip-address: true

